name: Build & Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort ddt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint
        run: |
          isort --version-number
          isort . --check-only
          black --version
          black . --check
      - name: Unittest
        run: |
          python -m unittest --verbose
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v1
      - uses: ikuanyshbekov/app-yaml-env-compiler@v1.0
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
          CLOUDSDK_CORE_DISABLE_PROMPTS: 1
        with:
          args: app deploy app.yaml
